### ISSUE TITLE
wrong ecmEnergy

### ISSUE THREAD

**Issue by mishaborodin** [retmas-dv/deftcore#6]
https://github.com/retmas-dv/deftcore/blob/14adf67e03cde0f6ab482688bad77e26a7bea417/taskengine/taskdef.py#L2408
change to                     
param_value = self._get_parameter_value(name, input_params)
                    if not param_value:
                        param_value = self._get_parameter_value(name, ctag)
                    if not param_value or str(param_value).lower() == 'none':
                        continue

**Comment by retmas-dv** [comment]
done.
